### ISSUE TITLE
Drop-down highlight breaks out of box

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#171]
The highlights (selected as well as hover) break out of the dropdown box.

![2016-02-15_21-48-05](https://cloud.githubusercontent.com/assets/1410238/13059932/0a427be4-d42e-11e5-8979-7a93c80d6d1c.png)

WebAnno -- 3.0.0-SNAPSHOT (2016-02-10 16:57:33, build 7101afd8131c583e5955772029ce169066cc95ad)

Safari Version 9.0.3 (11601.4.4)

**Comment by aakashysharma** [comment]
Isn't this fixed by #132 's fix?

**Comment by reckart** [comment]
Nope, still happens:

![2016-02-16_00-25-38](https://cloud.githubusercontent.com/assets/1410238/13063011/e202c01a-d443-11e5-971a-144491291e09.png)

**Comment by reckart** [comment]
Somebody may have fiddled around with CSS to break this - might be worth checking recent changes to CSS files. No idea where this comes from.

**Comment by reckart** [comment]
@ChrisBieTUDA @seyyaw Did you already observe this problem? Any idea what might have caused it?

**Comment by seyyaw** [comment]
This extending the drop-down box was requested by Eva. It was ugly but was agreed that it is better than hiding long texts, if I remember it correctly. BTW, what is github id of Eva?

**Comment by reckart** [comment]
This does not look like a feature - it looks like a glitch. 

If the annotation detail area is too small to show the text, then a functionality should be added to resize it.

We have tooltips now, right? So even if the text were too long here, then it would show up fully in the tooltip, no?

FYI @mmev

**Comment by reckart** [comment]
The offending commit is 0e5bf4dfc92efbbc8989749406ede7f55d06e060

The original user request:

> The drop-down lists menu for tagsets are often too narrow to see anything in the list.
See attachment.
> Currently, only the whole browser window can be resized by the user to cause a rerendering of the annotation interface, too. But the annotation panel is often still too narrow.
> Could be set the width of the right annotation panel (with the "Actions" and "Features" boxes) manually by the user?

Reverting this change since it looks like a glitch and it does not fulfill the original user request "being able to resize the width of the annotation detail panel".
